---
title: "Relational Data - Chap 10"
author: "Mac Faldet"
date: "November 9, 2017"
output: html_document
---

```{r setup, include=FALSE, echo=FALSE}
library(tidyverse)
library(readr)
library(dplyr)
library(nycflights13)
```

## Chapter 13 Relational Data

For nycflights13:

`flights` connects to planes via a single variable, `tailnum`.

`flights` connects to airlines through the `carrier` variable.

`flights` connects to airports in two ways: via the `origin` and `dest` variables.

`flights` connects to weather via `origin` (the location), and `year`, `month`, `day` and `hour` (the time).


Topics, functions:

  keys: `primary key`, `foreign key`,
  mutating joins: `left_join`, `right_join`, `inner_join`, `full_join`
merge vs. joins
  filtering joins: `semi_join`, `anti_join`
  set operations: `intersect`, `union`, `setdiff`


## 13.2.1 Exercises

1. Imagine you wanted to draw (approximately) the route each plane flies from its origin to its destination. What variables would you need? What tables would you need to combine?

  - We would need the `origin`, `dest`, and `carrier` variables in order to join on the *airplanes* and *airports* tibbles.

2. I forgot to draw the relationship between weather and airports. What is the relationship and how should it appear in the diagram?

  - you can match the variable `origin` in *weather* to `faa` in *airports*.

3. weather only contains information for the origin (NYC) airports. If it contained weather records for all airports in the USA, what additional relation would it define with flights?

  - `year`, `month`, `day`, `hour`, and `origin` would all additionally match.

4. We know that some days of the year are “special”, and fewer people than usual fly on them. How might you represent that data as a data frame? What would be the primary keys of that table? How would it connect to the existing tables?

  - I would create a tibble of special time frames in which a certain flighing behavior was expected to happen, then I would have it join to *flight* on `year`, `month`, `day`, and `hour` if needed.
  
  
## 13.3 Keys

There are two types of keys:

  - A _*primary key*_ uniquely identifies an observation in its own table. For example, planes$tailnum is a primary key because it uniquely identifies each plane in the planes table.

  - A _*foreign key*_ uniquely identifies an observation in another table. For example, the flights$tailnum is a foreign key because it appears in the flights table where it matches each flight to a unique plane.


## 13.3.1 Exercises

1. Add a surrogate key to flights.

```{surrogate r, echo=FALSE}
flights %>% 
  mutate(flight_id = row_number())
```

2. Identify the keys in the following datasets

  1. Lahman::Batting,
  2. babynames::babynames
  3. nasaweather::atmos
  4. fueleconomy::vehicles
  5. ggplot2::diamonds
(You might need to install some packages and read some documentation.)

  - The keys are grouped together below in a group by, proving themselves

```{keys r, echo=FALSE}
Lahman::Batting %>%
  group_by(playerID, yearID, stint) %>%
  filter(n() > 1) %>%
  nrow()

babynames::babynames %>%
  group_by(year, sex, name) %>%
  filter(n() > 1) %>%
  nrow()

nasaweather::atmos %>%
  group_by(lat, long, year, month) %>%
  filter(n() > 1) %>%
  nrow()

fueleconomy::vehicles %>%
  group_by(id) %>%
  filter(n() > 1) %>%
  nrow()

ggplot2::diamonds %>%
  distinct() %>% 
  nrow()
```

  - Note in diamonds: even using all variables there is still thousands of rows, there is no identifying variable.

3. Draw a diagram illustrating the connections between the Batting, Master, and Salaries tables in the Lahman package. Draw another diagram that shows the relationship between Master, Managers, AwardsManagers.

How would you characterise the relationship between the Batting, Pitching, and Fielding tables?

  - I would characterism them as very similar, given they are the only tables with a unique primary `stint` identifier that is unique for each player across leagues.
  
## 13.4.6 Exercises

1.  Compute the average delay by destination, then join on the airports data frame so you can show the spatial distribution of delays. Here’s an easy way to draw a map of the United States:

```{foursixone r,echo=TRUE}
airports %>%
  semi_join(flights, c("faa" = "dest")) %>%
  ggplot(aes(lon, lat)) +
    borders("state") +
    geom_point() +
    coord_quickmap()
```
(Don’t worry if you don’t understand what semi_join() does — you’ll learn about it next.)

You might want to use the size or colour of the points to display the average delay for each airport.

2.  Add the location of the origin and destination (i.e. the lat and lon) to flights.

3.  Is there a relationship between the age of a plane and its delays?

4.  What weather conditions make it more likely to see a delay?

5.  What happened on June 13 2013? Display the spatial pattern of delays, and then use Google to cross-reference with the weather.


  
## Mutating joins

```{mutationJoins r, echo=FALSE}
flights2 <- flights %>%
  select(year:day, hour, origin, dest, tailnum, carrier)
flights2 %>%
  select(-origin, -dest) %>%
  left_join(airlines, by = "carrier")
```

